module.exports.descriptors = [
    'Luxurious',
    'Historic',
    'Elegant',
    'Charming',
    'Rustic',
    'Spacious',
    'Modern',
    'Cozy',
    'Sleek',
    'Quaint',
    'Picturesque',
    'Boutique',
    'Exclusive',
    'Breathtaking',
    'Glamorous',
    'Stylish',
    'Tranquil',
    'Serene',
    'Secluded',
    'Exquisite',
    'Grand',
    'Trendy',
    'Cosmopolitan',
    'Traditional',
    'Artistic',
    'Sophisticated',
    'Eclectic',
    'Minimalist',
    'Opulent',
    'Historical',
    'Futuristic',
    'Retro',
    'Hip',
    'Vintage',
    'Bohemian',
    'Chic',
    'Majestic',
    'Romantic'
  ];
  
  module.exports.places = [
    'Hotel',
    'Resort',
    'Lodge',
    'Motel',
    'Inn',
    'Suites',
    'Spa',
    'Retreat',
    'Villas',
    'Palace',
    'Chateau',
    'Manor',
    'Estate',
    'Cottage',
    'Boutique Hotel',
    'Castle',
    'Hideaway',
    'Hostel',
    'Apartment Hotel',
    'Guesthouse',
    'B&B',
    'Ryokan',
    'Capsule Hotel',
    'Treehouse Hotel',
    'Glamping Site',
    'Beach Resort',
    'Mountain Lodge',
    'Boutique Inn',
    'Luxury Suites',
    'Floating Hotel',
    'Safari Lodge',
    'Historic Inn',
    'Eco-Resort',
    'Ski Lodge',
    'Desert Oasis',
    'Tropical Retreat',
    'City Hotel',
    'Barn Inn',
    'Seaside Resort',
    'Country House Hotel'
  ];
  